### ISSUE TITLE
Suggestion on inline tags

### ISSUE THREAD

**Issue by neitanod** [yosssi/gohtml#1]
It would be nice if some tags did not take their own lines, for instance, tags that are usually inline like: "a", "image", "span", "h1" and "h2" could be kept like this:

```
<p>
  Paragraph text with <span>an inline span element.</span>
</p>
```

**Comment by titpetric** [comment]
:+1:  on this, but seeing how you filed this issue in 2014 it's not likely to happen :(

**Comment by titpetric** [comment]
👍

**Comment by neitanod** [comment]
Yaay!

**Comment by nu8** [comment]
https://github.com/yosssi/gohtml/issues/19

**Comment by nu8** [comment]
This seems to have been broken at some point, as the original example now makes this:

~~~html
    <p>
      Paragraph text with
      <span>
        an inline span element.
      </span>
    </p>
~~~

I made a new issue
